### ISSUE TITLE
[ Expand All Sections ] [ Collapse All Sections ]

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-em-report-tool#74] opened 2021-09-17 13:39 UTC
To https://wcag-em-report-tool-2021-redesign.netlify.app/evaluation/audit-sample

I think we want to add [ Expand All Sections ] [ Collapse All Sections ] buttons **_either_**:
* at top and bottom of the ex-col area &mdash; that is, just twice on the page
* before each guideline &mdash; 4 times on page

_(I'd have to think more about the user experience to have a suggestion for which &mdash; and happy to go with editor & groups' perspective)_

Per https://wai-website-theme.netlify.app/components/excol/multiple/ that's done with 
```<div class="excol-all"></div>```

**Comment by shawna-slh** [comment] 2021-09-17 14:15
This might help the use case in https://github.com/w3c/wai-wcag-em-report-tool/issues/75

**Comment by shawna-slh** [comment] 2021-09-22 16:00
ah, now I see this was brought up in August https://github.com/w3c/wai-wcag-em-report-tool/issues/58

**Comment by hidde** [comment] 2021-09-22 16:15
Thanks Shawn, I think this is indeed a duplicate of #58, closing this in favour of that one as it was first.

**Comment by hidde** [comment] 2021-09-22 16:16
Also removing 'bug' label as it isn't a bug, it's an extra wish to enhance what's offered,.

**Closed by hidde** 2021-09-22 16:16 UTC
Labels: duplicate
