### ISSUE TITLE
QA check nothing else missing in redesign

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-wcag-em-report-tool#66] opened 2021-08-30 14:06 UTC
We discovered that something from the old tool was accidentally missing from the redesign. https://github.com/w3c/wai-wcag-em-report-tool/issues/65

Would be good to do a thorough check comparing the previous tool and the updated tool to see that nothing else is accidentally missing (as opposed to being left out on purpose). (And if left off on purpose, that should be documented so we know for the future!)

Does Hidde or Shadi need to do that? Or can they be point-of-contact for some else to do it?  Maybe Laura or **someone else in EOWG who has an eye for detail**!
ACTION: @sharronrush @bakkenb see if someone from EOWG can take this on

**Comment by sharronrush** [comment] 2021-08-30 14:43
I sent email to Laura and Hidde to see what they suggest as an approach.

**Comment by hidde** [comment] 2021-08-30 14:43
We have no baseline to QA against, such as a written out test plan with test cases/requirements for specific pieces of functionality. Without that, we could still “do QA”, but it will be as watertight as the testing we have done over the past year (i.e. not 100% watertight, as #65 shows). A test plan is best written by the person doing the QA, and that person is ideally not someone who's contributed to the code.

My suggestion would be to release first and be ready to fix problems when users report them. There are likely less bugs in `3.0.0` than in `2.*.*` and `3.0.0` fixes a lot of issues `2.*.*` had (see [fixed in 2021 redesign tag](https://github.com/w3c/wcag-em-report-tool/issues?q=is%3Aissue+is%3Aopen+label%3A%22priority+1%22+label%3A%22fixed+in+2021+redesign%22+)).

**Comment by bakkenb** [comment] 2021-08-30 16:05
I am on the fence about this. Part of me says release it as we know that it works and there may be little bugs we are made aware of that we can fix quite fast if Hidde will be able to do that. The other part says don't put something out that has (may have) bugs as it will be a reason for some people to be able to talk poorly about EOWG resources.

This is one reason why about two years ago I brought up the fact that when we do a thorough review of a tool, that we should ask all of our active participants to not just review the pages, but to use the tool as intended, and completely. Until we use it in anger we will not find many of the bugs. In my opinion, each participant should have picked a small sample of their own sites and completely used the tool to generate a report. Then reload the report and make edits.

When I originally suggested this it was for our accessibility statement generator tool. We didn't do it there either. If we don't do this, then the only way we truly know if there are bugs is to do thorough QA testing with test plans, or just wait for users to report bugs.

Again, still on the fence, but I wish we would add the requirement of fully using the tool in anger during the thorough review phase in the future.

**Closed** 2021-09-01 13:32 UTC
Labels: meta
