### ISSUE TITLE
Consider using localstorage for data persistency

### ISSUE THREAD

**Issue by joelanman** [w3c/wai-wcag-em-report-tool#71] opened 2021-09-14 11:01 UTC
I hadn't read the instructions fully, and assumed that as the data persisted from page to page, it was using some sort of storage and would persist if I closed the browser. I've lost quite a lot of work, my mistake, but I wonder if storage could be supported.

**Comment by hidde** [comment] 2021-09-23 14:14
Thanks for filing this!  It is a duplicate of #56, so will close this issue in favour of that one.

TLDR: we already support this in the ATAG Report Tool and should be able to add it to the WCAG-EM Report Tool in a feature iteration.

**Closed** 2021-09-23 14:14 UTC
Labels: duplicate
